#!/bin/bash

for i in {1..70}
do
	echo "<tr>"
		echo $'\t'"<td>Row $i col 1</td>"
		echo $'\t'"<td>Row $i col 2, longer data</td>"
		echo $'\t'"<td>Row $i col 3</td>"
		echo $'\t'"<td>Row $i col 4</td>"
	echo "</tr>"
done
